### ISSUE TITLE
"with" context manager macro?

### ISSUE THREAD

**Issue by wizzardx** [Yardanico/nimpylib#7]
Hi there!

I've managed to adapt the tut2 "withFile" template over to "withAs", eg like this:

```
template withAs(x: typed, y: untyped,
                body: untyped): typed =
  var x2 = x
  var y = x2.enter()
  try:
    body
  finally:
    x2.exit()

proc enter(f: File): File =
    echo "Entering context manager"
    return f

proc exit(f: File) =
    echo "Leaving context manager"
    f.close()

open("test.txt").withAs(f):
    echo f.readLine()
```
Could you add that to nimpylib perhaps?

Or even better, find a way with macros (like you did with "class") to be able to write that as:

```
with open("test.txt") as f:
    echo f.readLine()
```
Reference: This thread on the Nim forum:

https://forum.nim-lang.org/t/3205

**Comment by Udiknedormin** [comment]
It seems to me it would be much better as a macro for a variety of reasons:
- the syntax is more natural (for me it's always an important reason to write macros, actually)
- void-returns can be used equally easy
- binding and non-binding (no `as` part) are defined in one place with no collisions

Also, iterators can be included in this system in any of these ways:
- macro overloading for iterators
- generic enter and exit procs for iterators (can introduce collisions)
- iterator wrapper macro (similar to a macro decorator)

**Comment by Yardanico** [comment]
@juancarlospaco this issue doesn't talk ONLY about with open, it talks about "open" in general

**Comment by juancarlospaco** [comment]
Theres now `with` "in general" in stdlib, should be still consider this?. :thinking:

**Comment by wizzardx** [comment]
@juancarlospaco, I haven't been following the Nim stdlib closely. What do you mean by "with in general in stdlib"?

I'm aware of destructors, along with arc/orc memory manager that makes those more deterministic. Are you referring to that?

**Comment by juancarlospaco** [comment]
https://nim-lang.github.io/Nim/with.html

**Comment by wizzardx** [comment]
Thanks. That does something a bit different.

If the requested feature was still going to be implemented sometime into nimpylib, it might be better to name the macro "pythonicWith", in case both "nimpylib" and stdlib "with" are imported at the same time, eg:

```nim
import nimpylib
import with

import my_lib

pythonicWith my_open("/tmp/data.txt") as f:
  with f:
      write("ABC")
```
Which would turn after macro expansion into something like :

```nim
var x = my_open("/tmp/data.txt")
var context = enter(x)
context.write("ABC")
exit(context)
```
      
Where (the type for *context*), and procs for *enter* and *exit* need to be defined in *my_lib*. Not including exception handling and passing any exception details into the exit proc.

**Comment by Yardanico** [comment]
Has been implemented, although right now we still keep the name `with`. You can always choose to import stdlib's with with `as` syntax or fully qualificate both :)

**Comment by Yardanico** [comment]
Like that:
```nim
pylib.with open("testfile", fmReadWrite) as f:
  with f:
    write("helloworld")
```
